# The width of the terminal output in columns.
columns = 80
# Sort languages based on the specified column.
sort = "lines"
# Any doc strings (e.g. `"""hello"""` in python) will be counted as comments.
treat_doc_strings_as_comments = true
